version: '3'
services:
  eshiritori-ml:
    environment:
      PYTHONPATH: src/
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'eshiritori-ml'
    tty: true
    volumes:
      - .:/eshiritori-ml/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ['gpu']